[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
egg = "0.10.0"
env_logger = "0.11.6"
lazy_static = "1.5.0"
nom = "7.1.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
